modLoader = "javafml"
loaderVersion = "[36,)"
license = "whatever"
side = "CLIENT"

[[mods]]
modId = "metaslobus"
version = "1"
displayName = "metaslobus"
authors = "soumeh"

[[dependencies.metaslobus]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.metaslobus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "CLIENT"
